site_name: Platforms, Microservices, DevOps and APIs
site_author: Sandmann, H.
site_url: https://hsandmann.github.io/platform

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables

plugins:
  - glightbox
  - git-revision-date-localized
  - search
  - markdown-exec
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
nav:
  - Home: index.md
  - Versions:
    - 2024.1: ./versions/2024.1.md
  - Handout:
    - Roadmap: ./handout/roadmap.md
    - Account: ./handout/microservice-account.md
    - Auth: ./handout/microservice-auth.md
  - API:
    - Spring Boot Cloud: ./api/spring-boot-cloud.md
    - Testing: ./api/testing.md
    - Documentation: ./api/documentation.md
  - Platform:
    - Concepts: ./platform/concept.md
    - Microservices: ./platform/microservices.md
    - Discovery: ./platform/discovery.md
    - Gateway: ./platform/gateway.md
    - Config: ./platform/config.md
    - Load Balancing: ./platform/load-balancing.md
    - Circuit Breaker: ./platform/circuit-breaker.md
    - Security:
      - Concepts: ./platform/security/concepts.md
      - JWT: ./platform/security/jwt.md
      - OAuth2: ./platform/security/oauth2.md
      - Auth Service: ./platform/security/auth-service.md
      # - OpenID: openid.md
      # - SSO: sso.md
    - Communication: ./platform/communcation.md
    - Observability:
      - Monitoring: ./platform/observability/monitoring.md
      - Logging: ./platform/observability/logging.md
      - Tracing: ./platform/observability/tracing.md
    - Messaging: 
      - Concepts: ./platform/messaging/concepts.md
      - Kafka: ./platform/messaging/kafka.md
      - RabbitMQ: ./platform/messaging/rabbitmq.md
    - Database:
      - Flyway: ./platform/database/flyway.md
      - Caching: ./platform/database/caching.md
      # - MongoDB: mongodb.md
      # - Elasticsearch: elasticsearch.md
    - Payment: ./platform/payment.md
  - DevOps:
    - Concepts: ./devops/concepts.md
    - Version Control: ./devops/version-control-system.md
    - Docker: ./devops/docker.md
    - Packaging: ./devops/packaging.md
    - Release: ./devops/release.md
    # - Nexus: nexus.md
    # - SonarQube: sonarqube.md
    - Kubernetes: ./devops/kubernetes.md
  - Cloud Computing:
    - AWS: ./cloud/aws.md
    - GCP: ./cloud/gcp.md
    - Azure: ./cloud/azure.md
    - GitActions: ./cloud/gitactions.md
    - Terraform: ./cloud/terraform.md
  - Business:
    - Concepts: ./business/concepts.md
  - Appendix:
    - REST vs GraphQL: ./appendix/rest-vs-graphql.md
    - Versioning REST APIs: ./appendix/versioning-rest-apis.md
    - TLS for microservices: ./appendix/tls-for-microservices.md
  - Disclaimer: ./disclaimer.md
