site_name: Platforms, Microservices, DevOps and APIs
site_author: Sandmann, H.
site_url: https://hsandmann.github.io/platform
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.path
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables

plugins:
  - glightbox
nav:
  - Home: index.md
  - Versions:
    - 2024.1: 2024.1.md
  - API:
    - Spring Boot Cloud: spring-boot-cloud.md
    - Testing: testing.md
    - Documentation: documentation.md
  - Platform:
    - Concepts: platform.md
    - Microservices: microservices.md
    - Discovery: discovery.md
    - Gateway: gateway.md
    - Config: config.md
    - Load Balancing: load-balancing.md
    - Circuit Breaker: circuit-breaker.md
    - Security:
      - Concepts: security.md
      - JWT: jwt.md
      - OAuth2: oauth2.md
      # - OpenID: openid.md
      # - SSO: sso.md
    - Communication: communcation.md
    - Monitoring: monitoring.md
    - Logging: logging.md
    - Tracing: tracing.md
    - Messaging: 
      - Kafka: kafka.md
      - RabbitMQ: rabbitmq.md
    - Database:
      - Flyway: flyway.md
      - Redis: redis.md
      - MongoDB: mongodb.md
      - Elasticsearch: elasticsearch.md
    - Payments: payments.md
  - DevOps:
    - Concepts: devops.md
    - Build Automation: build-automation.md
    - Docker: docker.md
    - Git: git.md
    - CI/CD: cicd.md
    - Jenkins: jenkins.md
    - Nexus: nexus.md
    - SonarQube: sonarqube.md
    - Kubernetes: kubernetes.md
  - Cloud Computing:
    - Serverless: serverless.md
    - AWS: aws.md
    - Cloud Foundry: cloud-foundry.md
    - Google Cloud Platform: google-cloud-platform.md
    - Microsoft Azure: microsoft-azure.md
    - Terraform: terraform.md
  - Platform as an Innovation:
    - Concepts: platform-as-an-innovation.md
  - Appendix:
    - REST vs GraphQL: rest-vs-graphql.md
    - Versioning REST APIs: versioning-rest-apis.md
  - Contributors: contributors.md
